### ISSUE TITLE
Increasing poll interval

### ISSUE THREAD

**Issue by bcardarella** [andrewvy/chrome-launcher#9]
I've seen intermittent failures to detect that Chrome has launched. In almost all cases I suspect Chrome did launch but not fast enough. The current code appears to have a max timeout of 300ms (10 tries at 30ms each on master)

Looking at the chrome launcher by Google they are also using 10 tries but the delay is 500ms each: https://github.com/GoogleChrome/chrome-launcher/blob/master/chrome-launcher.ts#L119 so the total wait could be up to 5 seconds.

I've tried this size timeout locally and it does appear to clear up any issues I've seen with detecting the process starting.

**Comment by bcardarella** [comment]
Correction, they appear to do 50 retries: https://github.com/GoogleChrome/chrome-launcher/blob/master/chrome-launcher.ts#L120

They comment they have inline must be wrong: https://github.com/GoogleChrome/chrome-launcher/blob/master/chrome-launcher.ts#L258

So their total start up delay could be as long as 25 seconds.

**Comment by andrewvy** [comment]
Hey! Thanks for the info, I'm going to close this issue in favor of #8 to find a more holistic solution around this. :)
